services:
  app:
    image: jchanho99/backend-develop:latest
    container_name: springboot-backend
    restart: always
    network_mode: "host"
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    volumes:
      - ./app/leafresh-gcs.json:/app/leafresh-dev2.json:ro


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

