spring:
  datasource:
    url: jdbc:mysql://${DOCKER_LOCAL_DB_HOST}:${DB_PORT}/${DOCKER_LOCAL_DB_NAME}
    username: ${DOCKER_LOCAL_DB_USER}
    password: ${DOCKER_LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${DOCKER_LOCAL_CACHE_HOST}
      port: ${DOCKER_LOCAL_CACHE_PORT}

redis:
  redisson:
    address: redis://${SPRING_DATA_REDIS_HOST}:${SPRING_DATA_REDIS_PORT}
  bloom:
    host: ${DOCKER_LOCAL_CACHE_HOST}
    port: ${DOCKER_LOCAL_CACHE_PORT}

cookie:
  secure: true
  samesite: ${DOCKER_LOCAL_COOKIE_SAMESITE:none}
  domain: ${DOCKER_LOCAL_COOKIE_DOMAIN:.dev-leafresh.app}

gcp:
  project-id: ${GCP_PROJECT_ID}
  credentials:
    location: classpath:${GCP_CREDENTIALS_LOCATION}
  storage:
    bucket: ${GCP_STORAGE_BUCKET}
  pubsub:
    topics:
      order: ${GCP_PUBSUB_TOPIC_ORDER}
      image-verification: ${GCP_PUBSUB_TOPIC_IMAGE_VERIFICATION}
    subscriptions:
      order: ${GCP_PUBSUB_SUBSCRIPTION_ORDER}
      dlq: ${GCP_PUBSUB_SUBSCRIPTION_ORDER_DLQ}
      image-verification-result: ${GCP_PUBSUB_SUBSCRIPTION_IMAGE_VERIFICATION_RESULT}
      verification-dlq: ${GCP_PUBSUB_SUBSCRIPTION_IMAGE_VERIFICATION_RESULT_DLQ}
